### PR TITLE
Create Middleware and Route for Login and Profile

### PR DESCRIPTION
**Pull request by kjsninja**
Create a route for login and profile
Create middleware to validate session as allowHome and allowLogin
Add session validation for profile and login

### CODE REVIEW

**Review by jbpanganiban2 — APPROVED** [review]
I approve

**Review by jlmatienzo — APPROVED** [review]
reviewed

**Review by jlmatienzo — APPROVED** [review]

**Review by jbpanganiban2 — APPROVED** [review]
Approved again

**Review by qnx-victor-rafols — APPROVED** [review]

**Review by qnx-victor-rafols — APPROVED** [review]

**Review by qnx-victor-rafols — APPROVED** [review]
approved

**Review by qnx-victor-rafols — APPROVED** [review]
approved

**Review by jlmatienzo — APPROVED** [review]

**Review by jbpanganiban2 — APPROVED** [review]
Approved

**Review by qnx-victor-rafols — APPROVED** [review]
approved

**Pull request merged**
